"""Strategy Engine orchestrator for AI-driven strategy selection and execution.

Classifies market regime, selects and weights strategies based on rolling
performance, generates trade signals, scores confidence, and filters signals
through the overtrading guard.

Validates: Requirements 8.3, 8.7
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Protocol

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Protocols and Data Classes
# ---------------------------------------------------------------------------


class MarketRegime(Enum):
    """Market regime classifications."""

    TRENDING = "trending"
    RANGING = "ranging"
    VOLATILE = "volatile"
    CRISIS = "crisis"


@dataclass
class TradeSignal:
    """A trade signal generated by a strategy.

    Attributes:
        instrument: The instrument identifier.
        direction: Trade direction ("LONG" or "SHORT").
        entry_price: Proposed entry price.
        stop_loss: Proposed stop loss price.
        take_profit: Primary take profit target.
        confidence: Confidence score (0-100).
        strategy_name: Name of the strategy that generated this signal.
        timestamp: When the signal was generated.
        indicators: Dict of indicator values used for the signal.
    """

    instrument: str
    direction: str
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: int
    strategy_name: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    indicators: dict[str, Any] = field(default_factory=dict)


@dataclass
class MarketData:
    """Market data snapshot for strategy processing.

    Attributes:
        instrument: The instrument identifier.
        bid: Current bid price.
        ask: Current ask price.
        timestamp: Tick timestamp.
        adx: ADX indicator value.
        bb_width: Bollinger Band width.
        atr_percentile: ATR percentile rank.
        indicators: Additional indicator values.
    """

    instrument: str
    bid: float
    ask: float
    timestamp: datetime
    adx: float = 0.0
    bb_width: float = 0.0
    atr_percentile: float = 0.0
    indicators: dict[str, Any] = field(default_factory=dict)


@dataclass
class AccountState:
    """Current account state for strategy decisions.

    Attributes:
        equity: Current account equity.
        open_positions: List of open position details.
        daily_pnl: Today's realized PnL.
    """

    equity: float
    open_positions: list[dict[str, Any]] = field(default_factory=list)
    daily_pnl: float = 0.0


class BaseStrategy(Protocol):
    """Protocol for trading strategy implementations."""

    @property
    def name(self) -> str:
        """Strategy name identifier."""
        ...

    def generate_signal(
        self, market_data: MarketData, account_state: AccountState
    ) -> TradeSignal | None:
        """Generate a trade signal from market data, or None if no signal."""
        ...

    def get_backtest_sharpe(self, regime: MarketRegime, window_days: int = 30) -> float:
        """Get the strategy's Sharpe ratio for the given regime over the window."""
        ...


class RegimeDetectorProtocol(Protocol):
    """Protocol for market regime detection."""

    def classify(self, adx: float, bb_width: float, atr_percentile: float) -> MarketRegime:
        """Classify the current market regime."""
        ...


class ConfidenceScorerProtocol(Protocol):
    """Protocol for confidence scoring."""

    def calculate(
        self,
        confirming_indicators: int,
        total_indicators: int,
        strategy_backtest_sharpe: float,
        regime_alignment_score: float,
    ) -> int:
        """Calculate base confidence score."""
        ...

    def should_reject(self, final_score: int, threshold: int = 60) -> bool:
        """Check if score is below threshold."""
        ...


class OvertradingGuardProtocol(Protocol):
    """Protocol for overtrading prevention."""

    def can_trade(
        self,
        strategy_name: str,
        instrument: str,
        current_time: datetime,
        recent_win_rate: float,
        is_hft_signal: bool = False,
    ) -> Any:
        """Check if a trade is allowed by overtrading rules."""
        ...


# ---------------------------------------------------------------------------
# Strategy Engine
# ---------------------------------------------------------------------------


class StrategyEngine:
    """Orchestrates strategy selection, weighting, and signal generation.

    Manages a portfolio of strategies, dynamically weighting them based on
    their performance in the current market regime. Processes market data
    through the pipeline: regime classification → strategy selection →
    signal generation → confidence scoring → overtrading filtering.

    Args:
        strategies: List of strategy instances implementing BaseStrategy.
        regime_detector: Regime classification component.
        confidence_scorer: Confidence scoring component.
        overtrading_guard: Overtrading prevention component.
    """

    def __init__(
        self,
        strategies: list[BaseStrategy],
        regime_detector: RegimeDetectorProtocol,
        confidence_scorer: ConfidenceScorerProtocol,
        overtrading_guard: OvertradingGuardProtocol,
    ) -> None:
        self._strategies = strategies
        self._regime_detector = regime_detector
        self._confidence_scorer = confidence_scorer
        self._overtrading_guard = overtrading_guard

        # Initialize equal weights for all strategies
        num_strategies = len(strategies)
        if num_strategies > 0:
            equal_weight = 1.0 / num_strategies
            self._strategy_weights: dict[str, float] = {
                s.name: equal_weight for s in strategies
            }
        else:
            self._strategy_weights = {}

        self._current_regime: MarketRegime = MarketRegime.RANGING
        self._reweighting_in_progress: bool = False

    @property
    def strategy_weights(self) -> dict[str, float]:
        """Current strategy weights (sum to 1.0)."""
        return dict(self._strategy_weights)

    @property
    def current_regime(self) -> MarketRegime:
        """Currently detected market regime."""
        return self._current_regime

    async def process_market_data(
        self, market_data: MarketData, account_state: AccountState
    ) -> list[TradeSignal]:
        """Process market data through the full strategy pipeline.

        Pipeline steps:
        1. Classify market regime
        2. Select strategies appropriate for the regime
        3. Generate signals from selected strategies
        4. Score confidence for each signal
        5. Filter through overtrading guard

        Args:
            market_data: Current market data snapshot.
            account_state: Current account state.

        Returns:
            List of validated trade signals that passed all filters.
        """
        # Step 1: Classify regime
        new_regime = self._regime_detector.classify(
            adx=market_data.adx,
            bb_width=market_data.bb_width,
            atr_percentile=market_data.atr_percentile,
        )

        # If regime changed, reweight strategies
        if new_regime != self._current_regime:
            logger.info(
                "Regime change detected: %s → %s",
                self._current_regime.value,
                new_regime.value,
            )
            self._current_regime = new_regime
            self.reweight_strategies(new_regime, {})

        # Don't generate signals during reweighting
        if self._reweighting_in_progress:
            logger.info("Reweighting in progress, holding signals")
            return []

        # Step 2-3: Generate signals from all active strategies
        signals: list[TradeSignal] = []
        for strategy in self._strategies:
            weight = self._strategy_weights.get(strategy.name, 0.0)
            if weight <= 0.0:
                continue

            signal = strategy.generate_signal(market_data, account_state)
            if signal is not None:
                signals.append(signal)

        # Step 4: Score confidence and filter
        validated_signals: list[TradeSignal] = []
        for signal in signals:
            if self._confidence_scorer.should_reject(signal.confidence):
                logger.debug(
                    "Signal rejected (low confidence): strategy=%s confidence=%d",
                    signal.strategy_name,
                    signal.confidence,
                )
                continue

            # Step 5: Check overtrading guard
            trade_decision = self._overtrading_guard.can_trade(
                strategy_name=signal.strategy_name,
                instrument=signal.instrument,
                current_time=signal.timestamp,
                recent_win_rate=0.5,  # Default; real implementation would look up actual rate
            )

            if hasattr(trade_decision, "allowed") and not trade_decision.allowed:
                logger.debug(
                    "Signal blocked by overtrading guard: strategy=%s instrument=%s",
                    signal.strategy_name,
                    signal.instrument,
                )
                continue

            validated_signals.append(signal)

        logger.info(
            "Processed market data: regime=%s signals_generated=%d signals_validated=%d",
            self._current_regime.value,
            len(signals),
            len(validated_signals),
        )

        return validated_signals

    def reweight_strategies(
        self, regime: MarketRegime, performance_data: dict[str, float]
    ) -> None:
        """Reweight strategies based on 30-day rolling performance in detected regime.

        Weights are proportional to each strategy's risk-adjusted return (Sharpe ratio)
        in the current regime. Strategies with non-positive Sharpe get a minimum weight.
        All weights are normalized to sum to 1.0.

        Args:
            regime: The current market regime.
            performance_data: Dict mapping strategy name to its 30-day Sharpe ratio
                in the given regime. If empty, queries strategies directly.
        """
        self._reweighting_in_progress = True

        try:
            raw_weights: dict[str, float] = {}

            for strategy in self._strategies:
                name = strategy.name
                if name in performance_data:
                    sharpe = performance_data[name]
                else:
                    sharpe = strategy.get_backtest_sharpe(regime)

                # Use max(sharpe, 0.01) to avoid zero/negative weights
                # but still allow relative ranking
                raw_weights[name] = max(sharpe, 0.01)

            # Normalize to sum to 1.0
            total_weight = sum(raw_weights.values())
            if total_weight > 0:
                self._strategy_weights = {
                    name: weight / total_weight
                    for name, weight in raw_weights.items()
                }
            else:
                # Fallback to equal weights
                num = len(self._strategies)
                if num > 0:
                    self._strategy_weights = {
                        s.name: 1.0 / num for s in self._strategies
                    }

            logger.info(
                "Strategies reweighted for regime %s: %s",
                regime.value,
                self._strategy_weights,
            )
        finally:
            self._reweighting_in_progress = False

    def get_regime_alignment_score(
        self, signal_direction: str, regime: MarketRegime
    ) -> float:
        """Calculate alignment between signal direction and current regime.

        Args:
            signal_direction: "LONG" or "SHORT".
            regime: Current market regime.

        Returns:
            Alignment score between 0.0 and 1.0.
        """
        # Trending regime favors directional trades
        if regime == MarketRegime.TRENDING:
            return 0.9

        # Ranging regime is neutral
        if regime == MarketRegime.RANGING:
            return 0.5

        # Volatile regime slightly disfavors new entries
        if regime == MarketRegime.VOLATILE:
            return 0.3

        # Crisis regime strongly disfavors new entries
        if regime == MarketRegime.CRISIS:
            return 0.1

        return 0.5
