"""High-Frequency Trading (HFT) pipeline for tick-by-tick microstructure analysis.

Provides the HFTPipeline class that processes market ticks within a 10ms target,
detects microstructure signals (order flow imbalance, spread compression, momentum
micro-bursts), batches signals within a 100ms window, and submits orders in parallel.

Validates: Requirements 22.1, 22.2, 22.4, 22.5, 22.11, 22.12, 22.13
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from src.config.constants import (
    HFT_BATCH_WINDOW_MS,
    HFT_MAX_ORDER_RATE_DEFAULT,
    HFT_MAX_PER_INSTRUMENT_RATE,
    HFT_TICK_PROCESSING_TARGET_MS,
)

if TYPE_CHECKING:
    from src.core.event_bus import EventBus

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------


@dataclass
class HFTSignal:
    """A signal generated by the HFT microstructure analysis.

    Attributes:
        instrument: The instrument identifier.
        signal_type: Type of signal (order_flow_imbalance, spread_compression, momentum_burst).
        direction: Trade direction ("BUY" or "SELL").
        strength: Signal strength from 0.0 to 1.0.
        timestamp: When the signal was generated.
        tick_data: The raw tick data that generated this signal.
        latency_ms: Processing latency in milliseconds.
    """

    instrument: str
    signal_type: str
    direction: str
    strength: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    tick_data: dict[str, Any] = field(default_factory=dict)
    latency_ms: float = 0.0


@dataclass
class HFTMetrics:
    """Real-time HFT performance metrics.

    Attributes:
        orders_per_second: Current order submission rate.
        avg_latency_ms: Average tick processing latency in milliseconds.
        net_pnl_1min: Net PnL over the last 1 minute.
        net_pnl_5min: Net PnL over the last 5 minutes.
        net_pnl_daily: Net PnL for the current trading day.
        circuit_breaker_active: Whether the circuit breaker is currently active.
        total_exposure_pct: Current total HFT exposure as percentage of equity.
    """

    orders_per_second: float = 0.0
    avg_latency_ms: float = 0.0
    net_pnl_1min: Decimal = Decimal("0")
    net_pnl_5min: Decimal = Decimal("0")
    net_pnl_daily: Decimal = Decimal("0")
    circuit_breaker_active: bool = False
    total_exposure_pct: float = 0.0


# ---------------------------------------------------------------------------
# Sliding Window Counter
# ---------------------------------------------------------------------------


class SlidingWindowCounter:
    """Counts events within a sliding time window.

    Used for rate limiting: tracks how many orders have been submitted
    within the last second (or other configurable window).

    Args:
        window_seconds: The size of the sliding window in seconds.
    """

    def __init__(self, window_seconds: float = 1.0) -> None:
        self._window_seconds = window_seconds
        self._timestamps: list[float] = []

    def record(self) -> None:
        """Record an event at the current time."""
        self._timestamps.append(time.monotonic())
        self._prune()

    def count(self) -> int:
        """Return the number of events within the current window."""
        self._prune()
        return len(self._timestamps)

    def _prune(self) -> None:
        """Remove timestamps outside the sliding window."""
        cutoff = time.monotonic() - self._window_seconds
        self._timestamps = [t for t in self._timestamps if t > cutoff]


# ---------------------------------------------------------------------------
# HFT Pipeline
# ---------------------------------------------------------------------------


class HFTPipeline:
    """High-Frequency Trading pipeline for tick-by-tick microstructure analysis.

    Processes market ticks within a 10ms target, detects microstructure signals,
    batches them within a 100ms window, and submits orders in parallel.

    Args:
        max_order_rate: Maximum total orders per second (default 100).
        max_per_instrument_rate: Maximum orders per second per instrument (default 50).
        batch_window_ms: Batching window in milliseconds (default 100).
        event_bus: Optional EventBus for publishing HFT events.
    """

    def __init__(
        self,
        max_order_rate: int = HFT_MAX_ORDER_RATE_DEFAULT,
        max_per_instrument_rate: int = HFT_MAX_PER_INSTRUMENT_RATE,
        batch_window_ms: int = HFT_BATCH_WINDOW_MS,
        event_bus: "EventBus | None" = None,
    ) -> None:
        self.active: bool = False
        self._max_order_rate = max_order_rate
        self._max_per_instrument_rate = max_per_instrument_rate
        self._batch_window_ms = batch_window_ms
        self._event_bus = event_bus

        # Pre-warmed connection pool (minimum 5 persistent connections)
        self._connection_pool: list[dict[str, Any]] = []

        # Rate tracking
        self._order_rate_tracker = SlidingWindowCounter(window_seconds=1.0)
        self._instrument_rate_trackers: dict[str, SlidingWindowCounter] = {}

        # Batch buffer
        self._batch_buffer: list[HFTSignal] = []
        self._batch_lock = asyncio.Lock()

        # Latency tracking for metrics
        self._latency_samples: list[float] = []
        self._max_latency_samples = 1000

        # Mode change log
        self._mode_changes: list[dict[str, Any]] = []

        # Metrics
        self._metrics = HFTMetrics()

    # -------------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------------

    async def process_tick(self, tick: dict[str, Any]) -> list[HFTSignal]:
        """Process a single market tick through microstructure analysis.

        Performs order flow imbalance detection, spread compression identification,
        and momentum micro-burst detection within the 10ms processing target.

        Args:
            tick: Market tick data with keys: instrument, bid, ask, volume,
                  timestamp, bid_volume, ask_volume.

        Returns:
            List of HFTSignal instances generated from this tick.
        """
        if not self.active:
            return []

        start_time = time.perf_counter()
        signals: list[HFTSignal] = []
        instrument = tick.get("instrument", "UNKNOWN")

        # Order flow imbalance detection
        imbalance_signal = self._detect_order_flow_imbalance(tick)
        if imbalance_signal is not None:
            signals.append(imbalance_signal)

        # Spread compression identification
        spread_signal = self._detect_spread_compression(tick)
        if spread_signal is not None:
            signals.append(spread_signal)

        # Momentum micro-burst detection
        momentum_signal = self._detect_momentum_burst(tick)
        if momentum_signal is not None:
            signals.append(momentum_signal)

        # Record latency
        elapsed_ms = (time.perf_counter() - start_time) * 1000
        for signal in signals:
            signal.latency_ms = elapsed_ms

        self._record_latency(elapsed_ms)

        if elapsed_ms > HFT_TICK_PROCESSING_TARGET_MS:
            logger.warning(
                "HFT tick processing exceeded target: %.2fms > %dms for %s",
                elapsed_ms,
                HFT_TICK_PROCESSING_TARGET_MS,
                instrument,
            )

        return signals

    async def batch_and_submit(self, signals: list[HFTSignal]) -> list[dict[str, Any]]:
        """Batch signals within the configured window and submit in parallel.

        Signals are accumulated in the batch buffer. When the batch window
        expires, all buffered signals are submitted simultaneously.

        Args:
            signals: List of HFT signals to batch and submit.

        Returns:
            List of order submission results.
        """
        if not signals:
            return []

        async with self._batch_lock:
            self._batch_buffer.extend(signals)

        # Wait for batch window
        await asyncio.sleep(self._batch_window_ms / 1000.0)

        async with self._batch_lock:
            batch = self._batch_buffer.copy()
            self._batch_buffer.clear()

        if not batch:
            return []

        # Submit in parallel
        results = await asyncio.gather(
            *[self._submit_signal(signal) for signal in batch],
            return_exceptions=True,
        )

        submission_results: list[dict[str, Any]] = []
        for i, result in enumerate(results):
            if isinstance(result, Exception):
                submission_results.append(
                    {
                        "signal": batch[i].instrument,
                        "status": "error",
                        "error": str(result),
                    }
                )
            else:
                submission_results.append(result)
                self._order_rate_tracker.record()
                instrument = batch[i].instrument
                if instrument not in self._instrument_rate_trackers:
                    self._instrument_rate_trackers[instrument] = SlidingWindowCounter()
                self._instrument_rate_trackers[instrument].record()

        return submission_results

    async def enable(self, user: str, equity: Decimal) -> None:
        """Enable HFT mode with logging and connection pool warming.

        Args:
            user: The user or system that triggered the mode change.
            equity: Current account equity at time of enablement.
        """
        if self.active:
            logger.info("HFT mode already active, ignoring enable request")
            return

        self.active = True
        await self._warm_connection_pool()

        change_record = {
            "action": "enable",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "user": user,
            "equity": str(equity),
        }
        self._mode_changes.append(change_record)

        logger.info(
            "HFT mode enabled: user=%s equity=%s timestamp=%s",
            user,
            equity,
            change_record["timestamp"],
        )

        if self._event_bus is not None:
            await self._publish_event(
                "hft.mode_changed",
                {"action": "enable", "user": user, "equity": str(equity)},
            )

    async def disable(self, reason: str, user: str, equity: Decimal) -> None:
        """Disable HFT mode with logging and pending order drain.

        Args:
            reason: Reason for disabling HFT mode.
            user: The user or system that triggered the mode change.
            equity: Current account equity at time of disablement.
        """
        if not self.active:
            logger.info("HFT mode already inactive, ignoring disable request")
            return

        self.active = False

        # Drain pending orders from batch buffer
        async with self._batch_lock:
            pending_count = len(self._batch_buffer)
            self._batch_buffer.clear()

        change_record = {
            "action": "disable",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "user": user,
            "equity": str(equity),
            "reason": reason,
            "pending_orders_drained": pending_count,
        }
        self._mode_changes.append(change_record)

        logger.info(
            "HFT mode disabled: reason=%s user=%s equity=%s drained=%d",
            reason,
            user,
            equity,
            pending_count,
        )

        if self._event_bus is not None:
            await self._publish_event(
                "hft.mode_changed",
                {
                    "action": "disable",
                    "user": user,
                    "equity": str(equity),
                    "reason": reason,
                },
            )

    def check_rate_limit(self, instrument: str) -> bool:
        """Check if an order can proceed within rate limits.

        Returns True if both the global rate (max_order_rate/s) and
        per-instrument rate (max_per_instrument_rate/s) are within limits.

        Args:
            instrument: The instrument identifier to check.

        Returns:
            True if the order can proceed, False if rate limited.
        """
        # Check global rate
        if self._order_rate_tracker.count() >= self._max_order_rate:
            return False

        # Check per-instrument rate
        if instrument in self._instrument_rate_trackers:
            if (
                self._instrument_rate_trackers[instrument].count()
                >= self._max_per_instrument_rate
            ):
                return False

        return True

    def get_metrics(self) -> HFTMetrics:
        """Return current HFT metrics snapshot.

        Returns:
            HFTMetrics dataclass with current performance data.
        """
        self._metrics.orders_per_second = float(self._order_rate_tracker.count())
        self._metrics.avg_latency_ms = self._calculate_avg_latency()
        return self._metrics

    def update_metrics(
        self,
        net_pnl_1min: Decimal | None = None,
        net_pnl_5min: Decimal | None = None,
        net_pnl_daily: Decimal | None = None,
        circuit_breaker_active: bool | None = None,
        total_exposure_pct: float | None = None,
    ) -> None:
        """Update HFT metrics with external data.

        Args:
            net_pnl_1min: Net PnL over the last 1 minute.
            net_pnl_5min: Net PnL over the last 5 minutes.
            net_pnl_daily: Net PnL for the current trading day.
            circuit_breaker_active: Whether circuit breaker is active.
            total_exposure_pct: Current total HFT exposure percentage.
        """
        if net_pnl_1min is not None:
            self._metrics.net_pnl_1min = net_pnl_1min
        if net_pnl_5min is not None:
            self._metrics.net_pnl_5min = net_pnl_5min
        if net_pnl_daily is not None:
            self._metrics.net_pnl_daily = net_pnl_daily
        if circuit_breaker_active is not None:
            self._metrics.circuit_breaker_active = circuit_breaker_active
        if total_exposure_pct is not None:
            self._metrics.total_exposure_pct = total_exposure_pct

    async def publish_metrics(self) -> None:
        """Publish current HFT metrics to the Event Bus for real-time Dashboard updates.

        Collects the latest metrics snapshot and publishes it on the
        'hft.metrics_update' channel for consumption by the Dashboard.
        """
        metrics = self.get_metrics()
        payload = {
            "orders_per_second": metrics.orders_per_second,
            "avg_latency_ms": metrics.avg_latency_ms,
            "net_pnl_1min": str(metrics.net_pnl_1min),
            "net_pnl_5min": str(metrics.net_pnl_5min),
            "net_pnl_daily": str(metrics.net_pnl_daily),
            "circuit_breaker_active": metrics.circuit_breaker_active,
            "total_exposure_pct": metrics.total_exposure_pct,
        }
        await self._publish_event("hft.metrics_update", payload)

    @property
    def mode_changes(self) -> list[dict[str, Any]]:
        """Return the log of HFT mode changes."""
        return self._mode_changes.copy()

    # -------------------------------------------------------------------------
    # Microstructure Analysis
    # -------------------------------------------------------------------------

    def _detect_order_flow_imbalance(self, tick: dict[str, Any]) -> HFTSignal | None:
        """Detect order flow imbalance from bid/ask volume data.

        An imbalance is detected when the ratio of bid_volume to ask_volume
        (or vice versa) exceeds a threshold, indicating directional pressure.

        Args:
            tick: Market tick with bid_volume and ask_volume fields.

        Returns:
            HFTSignal if imbalance detected, None otherwise.
        """
        bid_volume = tick.get("bid_volume", 0)
        ask_volume = tick.get("ask_volume", 0)
        instrument = tick.get("instrument", "UNKNOWN")

        if bid_volume == 0 and ask_volume == 0:
            return None

        total_volume = bid_volume + ask_volume
        if total_volume == 0:
            return None

        imbalance_ratio = (bid_volume - ask_volume) / total_volume

        # Threshold: significant imbalance at > 0.6 or < -0.6
        if abs(imbalance_ratio) > 0.6:
            direction = "BUY" if imbalance_ratio > 0 else "SELL"
            strength = min(abs(imbalance_ratio), 1.0)
            return HFTSignal(
                instrument=instrument,
                signal_type="order_flow_imbalance",
                direction=direction,
                strength=strength,
                tick_data=tick,
            )

        return None

    def _detect_spread_compression(self, tick: dict[str, Any]) -> HFTSignal | None:
        """Detect spread compression indicating potential breakout.

        Spread compression occurs when the bid-ask spread narrows significantly,
        often preceding a directional move.

        Args:
            tick: Market tick with bid, ask, and avg_spread fields.

        Returns:
            HFTSignal if spread compression detected, None otherwise.
        """
        bid = tick.get("bid", 0)
        ask = tick.get("ask", 0)
        avg_spread = tick.get("avg_spread", 0)
        instrument = tick.get("instrument", "UNKNOWN")

        if avg_spread <= 0:
            return None

        current_spread = ask - bid
        if current_spread <= 0:
            return None

        compression_ratio = current_spread / avg_spread

        # Spread compressed to less than 40% of average
        if compression_ratio < 0.4:
            # Direction based on recent price movement
            last_mid = tick.get("last_mid", (bid + ask) / 2)
            current_mid = (bid + ask) / 2
            direction = "BUY" if current_mid >= last_mid else "SELL"
            strength = 1.0 - compression_ratio  # Higher compression = stronger signal

            return HFTSignal(
                instrument=instrument,
                signal_type="spread_compression",
                direction=direction,
                strength=strength,
                tick_data=tick,
            )

        return None

    def _detect_momentum_burst(self, tick: dict[str, Any]) -> HFTSignal | None:
        """Detect momentum micro-burst from rapid price movement.

        A momentum burst is detected when the price moves significantly
        within a very short time frame, indicating strong directional momentum.

        Args:
            tick: Market tick with price_change_pct field.

        Returns:
            HFTSignal if momentum burst detected, None otherwise.
        """
        price_change_pct = tick.get("price_change_pct", 0.0)
        instrument = tick.get("instrument", "UNKNOWN")

        # Threshold: > 0.1% move in a single tick
        if abs(price_change_pct) > 0.001:
            direction = "BUY" if price_change_pct > 0 else "SELL"
            strength = min(abs(price_change_pct) * 100, 1.0)  # Normalize to [0, 1]

            return HFTSignal(
                instrument=instrument,
                signal_type="momentum_burst",
                direction=direction,
                strength=strength,
                tick_data=tick,
            )

        return None

    # -------------------------------------------------------------------------
    # Connection Pool
    # -------------------------------------------------------------------------

    async def _warm_connection_pool(self) -> None:
        """Pre-warm the connection pool with minimum 5 persistent connections."""
        min_connections = 5
        while len(self._connection_pool) < min_connections:
            connection = {
                "id": len(self._connection_pool),
                "created_at": datetime.now(timezone.utc).isoformat(),
                "status": "ready",
            }
            self._connection_pool.append(connection)

        logger.info(
            "Connection pool warmed: %d connections ready",
            len(self._connection_pool),
        )

    # -------------------------------------------------------------------------
    # Order Submission
    # -------------------------------------------------------------------------

    async def _submit_signal(self, signal: HFTSignal) -> dict[str, Any]:
        """Submit a single HFT signal as an order.

        Args:
            signal: The HFT signal to submit.

        Returns:
            Dict with submission result.
        """
        return {
            "instrument": signal.instrument,
            "direction": signal.direction,
            "signal_type": signal.signal_type,
            "strength": signal.strength,
            "status": "submitted",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    # -------------------------------------------------------------------------
    # Metrics Helpers
    # -------------------------------------------------------------------------

    def _record_latency(self, latency_ms: float) -> None:
        """Record a latency sample for metrics calculation."""
        self._latency_samples.append(latency_ms)
        if len(self._latency_samples) > self._max_latency_samples:
            self._latency_samples = self._latency_samples[-self._max_latency_samples:]

    def _calculate_avg_latency(self) -> float:
        """Calculate average latency from recent samples."""
        if not self._latency_samples:
            return 0.0
        return sum(self._latency_samples) / len(self._latency_samples)

    # -------------------------------------------------------------------------
    # Event Publishing
    # -------------------------------------------------------------------------

    async def _publish_event(self, event_type: str, payload: dict[str, Any]) -> None:
        """Publish an HFT event to the Event Bus."""
        if self._event_bus is None:
            return

        try:
            from src.core.event_bus import Event

            event = Event(event_type=event_type, payload=payload)
            await self._event_bus.publish(event_type, event)
        except Exception as e:
            logger.error("Failed to publish HFT event: %s", str(e))
