"""Abstract base strategy interface and TradeSignal dataclass.

Defines the contract that all trading strategies must implement,
along with the TradeSignal data structure for signal communication.

Validates: Requirements 8.1
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from decimal import Decimal

import pandas as pd

from src.strategy.regime_detector import MarketRegime


@dataclass
class TradeSignal:
    """Represents a trade signal generated by a strategy.

    Attributes:
        instrument: The trading instrument identifier (e.g., "EUR/USD").
        direction: Trade direction, either "LONG" or "SHORT".
        entry_price: Suggested entry price.
        stop_loss: Stop loss price level.
        take_profit: Take profit price level.
        confidence_inputs: Dictionary of indicator values used for confidence scoring.
        strategy_name: Name of the strategy that generated this signal.
        regime: Current market regime when signal was generated.
    """

    instrument: str
    direction: str  # "LONG" or "SHORT"
    entry_price: Decimal
    stop_loss: Decimal
    take_profit: Decimal
    confidence_inputs: dict = field(default_factory=dict)
    strategy_name: str = ""
    regime: str = ""


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    All strategies must implement generate_signal() and get_indicators().
    The base class provides a helper for counting confirming indicators.
    """

    name: str = "base"

    @abstractmethod
    def generate_signal(
        self, market_data: pd.DataFrame, regime: MarketRegime
    ) -> TradeSignal | None:
        """Generate a trade signal based on market data and current regime.

        Args:
            market_data: DataFrame with OHLCV price data. Expected columns:
                open, high, low, close, volume (volume may be 0 for some instruments).
            regime: Current market regime classification.

        Returns:
            A TradeSignal if conditions are met, None otherwise.
        """
        ...

    @abstractmethod
    def get_indicators(self, market_data: pd.DataFrame) -> dict[str, float]:
        """Calculate and return all indicator values for the current market data.

        Args:
            market_data: DataFrame with OHLCV price data.

        Returns:
            Dictionary mapping indicator names to their current values.
        """
        ...

    def get_confirming_indicator_count(self, indicators: dict) -> tuple[int, int]:
        """Count how many indicators confirm the trade direction.

        Indicators are considered confirming if their value is truthy (non-zero,
        non-None). Each strategy should populate indicators with boolean-like
        values indicating confirmation.

        Args:
            indicators: Dictionary of indicator name -> value pairs.
                Values that evaluate to True are considered confirming.

        Returns:
            Tuple of (confirming_count, total_count).
        """
        total = len(indicators)
        confirming = sum(1 for v in indicators.values() if v)
        return confirming, total
